In [556]:
%load_ext autoreload
%autoreload 2
import glob
#from cleaning_data import cleaning_match
import pandas as pd
from feature_extraction import extracting_total_outs_per_batsman, runs_per_season, all_features

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

/Users/panesar47/galvanize/Performance-predictor-IPL/src

In [28]:
df_match_1 = pd.read_csv('data/1082591.csv',sep="/t")

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

In [200]:
match_venue = df_match_1.iloc[7]
match_toss = df_match_1.iloc[9]
match_toss_decision = df_match_1.iloc[10]
match_MOM = df_match_1.iloc[11]
team_won = df_match_1.iloc[17]
match_result_description = df_match_1.iloc[18]

In [61]:
match_date = df_match_1.iloc[4]

In [62]:
match_season = df_match_1.iloc[3]

In [63]:
match_date

version,1.3.0    info,date,2017/04/05
Name: 4, dtype: object

In [47]:
df = innings.join(innings['version,1.3.0'].str.split(',', expand=True).add_prefix('sec'))

In [52]:
match_1 = innings['version,1.3.0'].str.split(',', expand = True).add_prefix('sec')

In [64]:
match_1.rename(columns = {'sec1': 'balls', 'sec2':'over_ball','sec3':'batting_team', 'sec4':'batsman_striker', 'sec5':'batsman_non_striker', 'sec6':'bowler', 'sec7':'runs_scored', 'sec8':'extras?', 'sec9':'dissmisal_type','sec10':'batsman_out'}, inplace = True)

In [65]:
match_1

,sec0,balls,over_ball,batting_team,batsman_striker,batsman_non_striker,bowler,runs_scored,extras?,dissmisal_type,batsman_out
19,ball,1,0.1,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""",""""""
20,ball,1,0.2,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""",""""""
21,ball,1,0.3,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,4,0,"""""",""""""
22,ball,1,0.4,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""",""""""
23,ball,1,0.5,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,2,"""""",""""""
24,ball,1,0.6,Sunrisers Hyderabad,S Dhawan,DA Warner,TS Mills,0,0,"""""",""""""
25,ball,1,0.7,Sunrisers Hyderabad,S Dhawan,DA Warner,TS Mills,0,1,"""""",""""""
26,ball,1,1.1,Sunrisers Hyderabad,S Dhawan,DA Warner,A Choudhary,1,0,"""""",""""""
27,ball,1,1.2,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,4,0,"""""",""""""
28,ball,1,1.3,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,0,1,"""""",""""""
29,ball,1,1.4,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,6,0,"""""",""""""
30,ball,1,1.5,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,0,0,caught,DA Warner
31,ball,1,1.6,Sunrisers Hyderabad,MC Henriques,S Dhawan,A Choudhary,0,0,"""""",""""""
32,ball,1,1.7,Sunrisers Hyderabad,MC Henriques,S Dhawan,A Choudhary,4,0,"""""",""""""
33,ball,1,2.1,Sunrisers Hyderabad,S Dhawan,MC Henriques,TS Mills,1,0,"""""",""""""
34,ball,1,2.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,0,0,"""""",""""""
35,ball,1,2.3,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,0,0,"""""",""""""
36,ball,1,2.4,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,3,0,"""""",""""""
37,ball,1,2.5,Sunrisers Hyderabad,S Dhawan,MC Henriques,TS Mills,1,0,"""""",""""""
38,ball,1,2.6,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,1,0,"""""",""""""
39,ball,1,3.1,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,0,0,"""""",""""""
40,ball,1,3.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,1,0,"""""",""""""
41,ball,1,3.3,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,0,0,"""""",""""""
42,ball,1,3.4,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,1,0,"""""",""""""
43,ball,1,3.5,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,1,0,"""""",""""""
44,ball,1,3.6,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,1,0,"""""",""""""
45,ball,1,4.1,Sunrisers Hyderabad,S Dhawan,MC Henriques,S Aravind,1,0,"""""",""""""
46,ball,1,4.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,S Aravind,1,0,"""""",""""""
47,ball,1,4.3,Sunrisers Hyderabad,S Dhawan,MC Henriques,S Aravind,1,0,"""""",""""""
48,ball,1,4.4,Sunrisers Hyderabad,MC Henriques,S Dhawan,S Aravind,2,0,"""""",""""""
...,...,...,...,...,...,...,...,...,...,...,...
237,ball,2,14.5,Royal Challengers Bangalore,STR Binny,SR Watson,Rashid Khan,1,0,"""""",""""""
238,ball,2,14.6,Royal Challengers Bangalore,SR Watson,STR Binny,Rashid Khan,6,0,"""""",""""""
239,ball,2,15.1,Royal Challengers Bangalore,STR Binny,SR Watson,BCJ Cutting,0,0,"""""",""""""
240,ball,2,15.2,Royal Challengers Bangalore,STR Binny,SR Watson,BCJ Cutting,6,0,"""""",""""""
241,ball,2,15.3,Royal Challengers Bangalore,STR Binny,SR Watson,BCJ Cutting,1,0,"""""",""""""
242,ball,2,15.4,Royal Challengers Bangalore,SR Watson,STR Binny,BCJ Cutting,0,0,"""""",""""""
243,ball,2,15.5,Royal Challengers Bangalore,SR Watson,STR Binny,BCJ Cutting,4,0,"""""",""""""
244,ball,2,15.6,Royal Challengers Bangalore,SR Watson,STR Binny,BCJ Cutting,1,0,"""""",""""""
245,ball,2,16.1,Royal Challengers Bangalore,SR Watson,STR Binny,B Kumar,1,0,"""""",""""""
246,ball,2,16.2,Royal Challengers Bangalore,STR Binny,SR Watson,B Kumar,1,0,"""""",""""""
247,ball,2,16.3,Royal Challengers Bangalore,SR Watson,STR Binny,B Kumar,0,0,"""""",""""""
248,ball,2,16.4,Royal Challengers Bangalore,SR Watson,STR Binny,B Kumar,1,0,"""""",""""""
249,ball,2,16.5,Royal Challengers Bangalore,STR Binny,SR Watson,B Kumar,0,0,caught,STR Binny
250,ball,2,16.6,Royal Challengers Bangalore,S Aravind,SR Watson,B Kumar,0,0,"""""",""""""
251,ball,2,17.1,Royal Challengers Bangalore,SR Watson,S Aravind,A Nehra,2,0,"""""",""""""
252,ball,2,17.2,Royal Challengers Bangalore,SR Watson,S Aravind,A Nehra,0,0,"""""",""""""
253,ball,2,17.3,Royal Challengers Bangalore,SR Watson,S Aravind,A Nehra,0,0,caught,SR Watson
254,ball,2,17.4,Royal Challengers Bangalore,S Aravind,TS Mills,A Nehra,0,0,bowled,S Aravind
255,ball,2,17.5,Royal Challengers Bangalore,YS Chahal,TS Mills,A Nehra,0,0,"""""",""""""
256,ball,2,17.6,Royal Challengers Bangalore,YS Chahal,TS Mills,A Nehra,0,0,"""""",""""""
257,ball,2,18.1,Royal Challengers Bangalore,TS Mills,YS Chahal,B Kumar,0,1,"""""",""""""
258,ball,2,18.2,Royal Challengers Bangalore,YS Chahal,TS Mills,B Kumar,0,0,"""""",""""""
259,ball,2,18.3,Royal Challengers Bangalore,YS Chahal,TS Mills,B Kumar,1,0,"""""",""""""
260,ball,2,18.4,Royal Challengers Bangalore,TS Mills,YS Chahal,B Kumar,6,0,"""""",""""""
261,ball,2,18.5,Royal Challengers Bangalore,TS Mills,YS Chahal,B Kumar,0,0,caught,TS Mills
262,ball,2,18.6,Royal Challengers Bangalore,YS Chahal,A Choudhary,B Kumar,1,0,"""""",""""""
263,ball,2,19.1,Royal Challengers Bangalore,YS Chahal,A Choudhary,BCJ Cutting,0,0,"""""",""""""
264,ball,2,19.2,Royal Challengers Bangalore,YS Chahal,A Choudhary,BCJ Cutting,1,0,"""""",""""""
265,ball,2,19.3,Royal Challengers Bangalore,A Choudhary,YS Chahal,BCJ Cutting,6,0,"""""",""""""
266,ball,2,19.4,Royal Challengers Bangalore,A Choudhary,YS Chahal,BCJ Cutting,0,0,run out,YS Chahal

### extrating date, season, etc. from the table

In [97]:
match_1.drop('date', axis = 1, inplace = True)

In [127]:

date = match_date[0]
date

date  = date.split('date,')[1]

date

'2017/04/05'

### extracting season from the table

In [112]:
season = match_season[0]
season  = season.split('season,')[1]
# season

In [218]:
match_venue = df_match_1.iloc[7]
match_toss = df_match_1.iloc[9]
match_toss_decision = df_match_1.iloc[10]
match_MOM = df_match_1.iloc[11]
team_won = df_match_1.iloc[17]
match_result_description = df_match_1.iloc[18]

In [219]:
match_venue = match_venue[0]
match_toss = match_toss[0]
match_toss_decision = match_toss_decision[0]
MOM = match_MOM[0]
team_won = team_won[0]
match_result_description = match_result_description[0]

match_venue  = match_venue.split('venue,')[1]
match_toss  = match_toss.split('toss_winner,')[1]
match_toss_decision  = match_toss_decision.split('toss_decision,')[1]
player_of_the_match  = MOM.split('player_of_match,')[1]
team_won  = team_won.split('winner,')[1]
match_result_description  = match_result_description.split('info,')[1]

'info,player_of_match,Yuvraj Singh'

### adding match, season etc.to the dataframe

In [128]:
match_1['date'] = date


match_1['season']= season

In [220]:
match_1['match_venue']= match_venue
match_1['match_toss_winner']= match_toss
match_1['match_toss_decision']= match_toss_decision
match_1['player_of_the_match']= player_of_the_match
match_1['team_won']= team_won
match_1['match_result_description']= match_result_description

In [221]:
match_1.head()

,over_ball,batting_team,batsman_striker,batsman_non_striker,bowler,runs_scored,extras?,dissmisal_type,batsman_out,date,season,match_venue,match_toss_winner,match_toss_decision,player_of_the_match,team_won,match_result_description
19,0.1,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""",2017/04/05,2017,"""Rajiv Gandhi International Stadium, Uppal""",Royal Challengers Bangalore,field,Yuvraj Singh,Sunrisers Hyderabad,"winner_runs,35"
20,0.2,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""",2017/04/05,2017,"""Rajiv Gandhi International Stadium, Uppal""",Royal Challengers Bangalore,field,Yuvraj Singh,Sunrisers Hyderabad,"winner_runs,35"
21,0.3,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,4,0,"""""","""""",2017/04/05,2017,"""Rajiv Gandhi International Stadium, Uppal""",Royal Challengers Bangalore,field,Yuvraj Singh,Sunrisers Hyderabad,"winner_runs,35"
22,0.4,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""",2017/04/05,2017,"""Rajiv Gandhi International Stadium, Uppal""",Royal Challengers Bangalore,field,Yuvraj Singh,Sunrisers Hyderabad,"winner_runs,35"
23,0.5,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,2,"""""","""""",2017/04/05,2017,"""Rajiv Gandhi International Stadium, Uppal""",Royal Challengers Bangalore,field,Yuvraj Singh,Sunrisers Hyderabad,"winner_runs,35"

In [132]:
match_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 19 to 266
Data columns (total 13 columns):
sec0                   248 non-null object
balls                  248 non-null object
over_ball              248 non-null object
batting_team           248 non-null object
batsman_striker        248 non-null object
batsman_non_striker    248 non-null object
bowler                 248 non-null object
runs_scored            248 non-null object
extras?                248 non-null object
dissmisal_type         248 non-null object
batsman_out            248 non-null object
date                   248 non-null object
season                 248 non-null object
dtypes: object(13)
memory usage: 25.3+ KB

In [135]:
match_1.head()

,sec0,balls,over_ball,batting_team,batsman_striker,batsman_non_striker,bowler,runs_scored,extras?,dissmisal_type,batsman_out,date,season
19,ball,1,0.1,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""",2017/04/05,2017
20,ball,1,0.2,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""",2017/04/05,2017
21,ball,1,0.3,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,4,0,"""""","""""",2017/04/05,2017
22,ball,1,0.4,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""",2017/04/05,2017
23,ball,1,0.5,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,2,"""""","""""",2017/04/05,2017

In [151]:
def cleaning(path):
    # reading with /t right now
    df = pd.read_csv(path,sep="/t")

    #extracting date
    match_date = df.iloc[4]
    date = match_date[0]
    date  = date.split('date,')[1]

    #extracting season
    match_season = df.iloc[3]
    season = match_season[0]
    season  = season.split('season,')[1]

    #cleaning data
    innings = df[19:]
    match_df= innings['version,1.3.0'].str.split(',', expand = True).add_prefix('sec')
    match_df.rename(columns = {'sec1': 'balls', 'sec2':'over_ball', 
                            'sec3':'batting_team', 'sec4':'batsman_striker', 
                            'sec5':'batsman_non_striker', 'sec6':'bowler', 
                            'sec7':'runs_scored', 'sec8':'extras?', 
                            'sec9':'dissmisal_type','sec10':'batsman_out'}, 
                            inplace = True)
    match_df.drop(['balls', 'sec0'] , axis = 1, inplace = True)

    #add season and date
    match_df['date'] = date
    match_df['season']= season

    return match_df

In [153]:
match_1 = cleaning('data/1082591.csv')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until

In [159]:
a = '108259'+'2'
s = []

In [160]:
for i in range(4):
    s.append(str(i))

In [174]:
# import glob


# path =r'data/Untitled Folder/' # use your path
# allFiles = glob.glob(path + "/*.csv")
# frame = pd.DataFrame()
# list_ = []
# for file_ in allFiles:
#     df = pd.read_csv(file_,sep= ","  ,index_col=None, header=0)
#     list_.append(df)
# frame = pd.concat(list_)

ParserError: Error tokenizing data. C error: Expected 3 fields in line 20, saw 11

In [179]:
for i in range(4:):
    print (i)

SyntaxError: invalid syntax (<ipython-input-179-08846cd607d1>, line 1)

In [189]:
files = []
for i in range(19,12, -2):
    files.append('981019'+str(i)+'.csv')

# path =r'C:\DRO\DCL_rawdata_files' # use your path
# allFiles = glob.glob(path + "/*.csv")
# frame = pd.DataFrame()
# list_ = []
# for file_ in allFiles:
#     df = pd.read_csv(file_,index_col=None, header=0)
#     list_.append(df)
# frame = pd.concat(list_)
dfs = []
for file in files:
    dfs.append(df = pd.read(file)

In [191]:
# import glob
# import pandas as pd
# import numpy as np

# files = glob.glob('folder/*.csv')
# for file in files:
#     df = pd.read_csv(file)

# #make conversion
# df['Time taken'] = pd.to_datetime(df['Time taken'])
# df['Time taken'] = df['Time taken'].dt.hour + df['Time taken'].dt.minute / 60

# #output file
# df.to_csv('*.csv', index = False)

/Users/panesar47/galvanize/capstone_project/ipl_csv

In [47]:
import pandas as  pd
# import glob

# files = glob.glob('folder/*.csv')
# for file in files:
#     cleaning_match(file)

def cleaning_match(path):
    # reading with /t right now
    df = pd.read_csv(path,sep="/t")

    #extracting future columns from info
    match_date = df.iloc[4]
    match_season = df.iloc[3]
    match_venue = df.iloc[7]
    match_toss = df.iloc[9]
    match_toss_decision = df.iloc[10]
    match_MOM = df.iloc[11]
    team_won = df.iloc[17]
    match_result_description = df.iloc[18]

    #step2
    date = match_date[0]
    season = match_season[0]
    match_venue = match_venue[0]
    match_toss = match_toss[0]
    match_toss_decision = match_toss_decision[0]
    MOM = match_MOM[0]
    team_won = team_won[0]
    match_result_description = match_result_description[0]

    #step3
#     date  = date.split('date,')[1]
#     season  = season.split('season,')[1]
# #     #match_venue  = match_venue.split('venue,')[1]
#     match_toss  = match_toss.split('toss_winner,')[1]
#     match_toss_decision  = match_toss_decision.split('toss_decision,')[1]
#     player_of_the_match  = MOM.split('player_of_match,')[1]
#     team_won  = team_won.split('winner,')[1]
   # match_result_description  = match_result_description.split('info,')[1]



    #cleaning data
    innings = df[19:]
    match_df= innings['version,1.3.0'].str.split(',', expand = True).add_prefix('sec')
    match_df.rename(columns = {'sec1': 'balls', 'sec2':'over_ball',
                            'sec3':'batting_team', 'sec4':'batsman_striker',
                            'sec5':'batsman_non_striker', 'sec6':'bowler',
                            'sec7':'runs_scored', 'sec8':'extras?',
                            'sec9':'dissmisal_type','sec10':'batsman_out'},
                            inplace = True)
    match_df.drop(['balls', 'sec0'] , axis = 1, inplace = True)

    #add columns to data frame
    match_df['match_venue']= match_venue
    match_df['match_toss_winner']= match_toss
    match_df['match_toss_decision']= match_toss_decision
#     match_df['player_of_the_match']= player_of_the_match
#     match_df['team_won']= team_won
#     match_df['match_result_description']= match_result_description
    match_df['date'] = date
    match_df['season']= season


    return match_df
#.to_csv("Output-" + file, na_rep='NaN'*.csv', index = False)
# df.to_csv('*.csv', index = False)
#df.to_csv(os.path.basename(file) + "-processed.csv", na_rep='NaN')

In [51]:
pwd

'/Users/panesar47/galvanize/capstone_project/ipl_csv'

In [52]:
import glob
#!cd Data/Untitled_Folder/
files = glob.glob('Data/Untitled_Folder/*.csv')
for file in files:
    df = cleaning_match(file)
    df.to_csv("Output-" + file, na_rep='NaN')

    #df.to_csv('updated_{}'.format(file), index = False)

In [263]:
a = cleaning_match('data/336039.csv')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

In [237]:
a.to_csv('Data/Untitled_Folder/out.csv')

In [171]:
from cleaning_data import cleaning_match

In [59]:
# for file in glob.glob('Data/Untitled_Folder/*.csv'):
#     df = cleaning_match(file)
#     df.to_csv(file)

def cleaning_replacing_trial(path):
    '''takes the path to the folder,cleans and replaces existing
    path example  = 'Data/Untitled_Folder/'''

    for file in glob.glob(path+'/*.csv'):
        df = cleaning_match(file)
        unique_id = (file.split('/')[-1]).split('.')[0]
        df['match_id']= unique_id
        


        df.to_csv(file, index = False)

In [83]:
 len(glob.glob('../../capstone_project/ipl_csv/Data/trial/'+'/*.csv'))

636

In [161]:
def cleaning_match(path):
    # reading with /t right now
    df = pd.read_csv(path,sep="/t")

    #extracting future columns from info
    # match_date = df.loc[4]#earlier 4
    # match_season = df.loc[3] #earlier 4
    # match_venue = df.loc[6]
    # match_toss = df.loc[8]
    # match_toss_decision = df.loc[9]
    # match_MOM = df.loc[10]
    # team_won = df.loc[16]
    # match_result_description = df.loc[17]
    
    #if (df.loc[6][0]).split(',')[1] =='match_number':
    match_date = df.loc[4]
    match_season = df.loc[3]
    match_venue = df.loc[7]
    match_toss = df.loc[9]
    match_toss_decision = df.loc[10]
    match_MOM = df.loc[11]
    team_won = df.loc[17]
    match_result_description = df.loc[18]

    #step2
    date = match_date[0]
    season = match_season[0]
    match_venue = match_venue[0]
    match_toss = match_toss[0]
    match_toss_decision = match_toss_decision[0]
    MOM = match_MOM[0]
    team_won = team_won[0]
    match_result_description = match_result_description[0]

    #step3
    print(date)
    date  = date.split('date,')[1]
    season  = season.split('season,')[1]
    print(match_venue)
    match_venue  = match_venue.split('venue,')[1]
    match_toss  = match_toss.split('toss_winner,')[1]
    match_toss_decision  = match_toss_decision.split('toss_decision,')[1]
    player_of_the_match  = MOM.split('player_of_match,')[1]
    team_won  = team_won.split('winner,')[1]
    match_result_description  = match_result_description.split('info,')[1]

    innings = df[:]
    match_df= innings['version,1.3.0'].str.split(',', expand = True).add_prefix('sec')
    match_df.rename(columns = {'sec1': 'balls', 'sec2':'over_ball',
                            'sec3':'batting_team', 'sec4':'batsman_striker',
                            'sec5':'batsman_non_striker', 'sec6':'bowler',
                            'sec7':'runs_scored', 'sec8':'extras?',
                            'sec9':'dissmisal_type','sec10':'batsman_out'},
                            inplace = True)
    match_df.drop(['balls', 'sec0'] , axis = 1, inplace = True)
    innings = df[19:]
    match_df= innings['version,1.3.0'].str.split(',', expand = True).add_prefix('sec')
    match_df.rename(columns = {'sec1': 'balls', 'sec2':'over_ball',
                            'sec3':'batting_team', 'sec4':'batsman_striker',
                            'sec5':'batsman_non_striker', 'sec6':'bowler',
                            'sec7':'runs_scored', 'sec8':'extras?',
                            'sec9':'dissmisal_type','sec10':'batsman_out'},
                            inplace = True)
    match_df.drop(['balls', 'sec0'] , axis = 1, inplace = True)

    match_df['match_venue']= match_venue
    match_df['match_toss_winner']= match_toss
    match_df['match_toss_decision']= match_toss_decision
    match_df['player_of_the_match']= player_of_the_match
    match_df['team_won']= team_won
    match_df['match_result_description']= match_result_description
    match_df['date'] = date
    match_df['season']= season

    return match_df

In [163]:
df = cleaning_match('Data/trial/981005.csv')

info,date,2016/05/21
info,venue,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until

In [179]:
df.loc[8][0]

'info,city,Bangalore'

### Running cleaning, replacing and concating code

In [150]:
from cleaning_data import cleaning_match, cleaning_replacing, concating_dataframes

In [151]:
cleaning_replacing('../../capstone_project/ipl_csv/Data/trial/')

/Users/panesar47/galvanize/Performance-predictor-IPL/src/cleaning_data.py:8: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv(path,sep="/t")

In [199]:
df_all_matches = concating_dataframes('../../capstone_project/ipl_csv/Data/trial/')

In [147]:
merging_dataframes('../../capstone_project/ipl_csv/Data/trial/')

,over_ball,batting_team,batsman_striker,batsman_non_striker,bowler,runs_scored,extra,dissmisal_type,batsman_out,match_venue,match_toss_winner,match_toss_decision,team_won,date,season,match_id
0,0.1,Gujarat Lions,JJ Roy,BB McCullum,TA Boult,0,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
1,0.2,Gujarat Lions,JJ Roy,BB McCullum,TA Boult,4,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
2,0.3,Gujarat Lions,JJ Roy,BB McCullum,TA Boult,0,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
3,0.4,Gujarat Lions,JJ Roy,BB McCullum,TA Boult,0,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
4,0.5,Gujarat Lions,JJ Roy,BB McCullum,TA Boult,4,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
5,0.6,Gujarat Lions,JJ Roy,BB McCullum,TA Boult,0,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
6,1.1,Gujarat Lions,BB McCullum,JJ Roy,PP Chawla,1,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
7,1.2,Gujarat Lions,JJ Roy,BB McCullum,PP Chawla,0,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
8,1.3,Gujarat Lions,JJ Roy,BB McCullum,PP Chawla,4,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
9,1.4,Gujarat Lions,JJ Roy,BB McCullum,PP Chawla,0,1,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
10,1.5,Gujarat Lions,JJ Roy,BB McCullum,PP Chawla,0,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
11,1.6,Gujarat Lions,JJ Roy,BB McCullum,PP Chawla,1,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
12,1.7,Gujarat Lions,BB McCullum,JJ Roy,PP Chawla,1,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
13,2.1,Gujarat Lions,BB McCullum,JJ Roy,SP Narine,0,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
14,2.2,Gujarat Lions,BB McCullum,JJ Roy,SP Narine,4,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
15,2.3,Gujarat Lions,BB McCullum,JJ Roy,SP Narine,0,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
16,2.4,Gujarat Lions,BB McCullum,JJ Roy,SP Narine,1,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
17,2.5,Gujarat Lions,JJ Roy,BB McCullum,SP Narine,1,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
18,2.6,Gujarat Lions,BB McCullum,JJ Roy,SP Narine,0,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
19,3.1,Gujarat Lions,JJ Roy,BB McCullum,PP Chawla,0,0,caught,JJ Roy,Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
20,3.2,Gujarat Lions,SK Raina,BB McCullum,PP Chawla,0,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
21,3.3,Gujarat Lions,SK Raina,BB McCullum,PP Chawla,1,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
22,3.4,Gujarat Lions,BB McCullum,SK Raina,PP Chawla,6,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
23,3.5,Gujarat Lions,BB McCullum,SK Raina,PP Chawla,0,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
24,3.6,Gujarat Lions,BB McCullum,SK Raina,PP Chawla,0,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
25,4.1,Gujarat Lions,SK Raina,BB McCullum,SP Narine,1,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
26,4.2,Gujarat Lions,BB McCullum,SK Raina,SP Narine,2,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
27,4.3,Gujarat Lions,BB McCullum,SK Raina,SP Narine,4,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
28,4.4,Gujarat Lions,BB McCullum,SK Raina,SP Narine,0,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
29,4.5,Gujarat Lions,BB McCullum,SK Raina,SP Narine,4,0,"""""","""""",Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,2017/04/07,2017,1082593
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,11.3,Rising Pune Supergiant,MS Dhoni,R Bhatia,A Mishra,1,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
197,11.4,Rising Pune Supergiant,R Bhatia,MS Dhoni,A Mishra,0,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
198,11.5,Rising Pune Supergiant,R Bhatia,MS Dhoni,A Mishra,1,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
199,11.6,Rising Pune Supergiant,MS Dhoni,R Bhatia,A Mishra,0,0,caught,MS Dhoni,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
200,12.1,Rising Pune Supergiant,R Bhatia,DL Chahar,PJ Cummins,0,1,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
201,12.2,Rising Pune Supergiant,DL Chahar,R Bhatia,PJ Cummins,0,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
202,12.3,Rising Pune Supergiant,DL Chahar,R Bhatia,PJ Cummins,1,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
203,12.4,Rising Pune Supergiant,R Bhatia,DL Chahar,PJ Cummins,1,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
204,12.5,Rising Pune Supergiant,DL Chahar,R Bhatia,PJ Cummins,6,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
205,12.6,Rising Pune Supergiant,DL Chahar,R Bhatia,PJ Cummins,6,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
206,13.1,Rising Pune Supergiant,R Bhatia,DL Chahar,A Mishra,0,0,caught,R Bhatia,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
207,13.2,Rising Pune Supergiant,A Zampa,DL Chahar,A Mishra,0,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
208,13.3,Rising Pune Supergiant,A Zampa,DL Chahar,A Mishra,1,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
209,13.4,Rising Pune Supergiant,DL Chahar,A Zampa,A Mishra,1,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
210,13.5,Rising Pune Supergiant,A Zampa,DL Chahar,A Mishra,4,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
211,13.6,Rising Pune Supergiant,A Zampa,DL Chahar,A Mishra,0,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
212,14.1,Rising Pune Supergiant,DL Chahar,A Zampa,Z Khan,0,0,caught,DL Chahar,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
213,14.2,Rising Pune Supergiant,AB Dinda,A Zampa,Z Khan,0,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
214,14.3,Rising Pune Supergiant,AB Dinda,A Zampa,Z Khan,4,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
215,14.4,Rising Pune Supergiant,AB Dinda,A Zampa,Z Khan,0,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
216,14.5,Rising Pune Supergiant,AB Dinda,A Zampa,Z Khan,0,1,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
217,14.6,Rising Pune Supergiant,AB Dinda,A Zampa,Z Khan,1,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
218,14.7,Rising Pune Supergiant,A Zampa,AB Dinda,Z Khan,0,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
219,15.1,Rising Pune Supergiant,AB Dinda,A Zampa,A Mishra,1,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
220,15.2,Rising Pune Supergiant,A Zampa,AB Dinda,A Mishra,0,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
221,15.3,Rising Pune Supergiant,A Zampa,AB Dinda,A Mishra,0,0,caught,A Zampa,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
222,15.4,Rising Pune Supergiant,AB Dinda,Imran Tahir,A Mishra,1,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
223,15.5,Rising Pune Supergiant,Imran Tahir,AB Dinda,A Mishra,0,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
224,15.6,Rising Pune Supergiant,Imran Tahir,AB Dinda,A Mishra,0,0,"""""","""""",Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599
225,16.1,Rising Pune Supergiant,AB Dinda,Imran Tahir,PJ Cummins,0,0,caught,AB Dinda,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Daredevils,2017/04/11,2017,1082599

In [149]:
def concating_dataframes(path):
    '''input: path to the folder with csv files
        output: concatenated all the files in one'''
    path = '../../capstone_project/ipl_csv/Data/trial/'
    allFiles = glob.glob(path + "/*.csv")
    frame = pd.DataFrame()
    list_ = []
    for file_ in allFiles:
        df = pd.read_csv(file_,index_col=None, header=0)
        list_.append(df)
    frame = pd.concat(list_)
    return frame

In [168]:
df.season.unique()

array([2017, '2007/08', 2009, '2009/10', 2011, 2012, 2013, 2014, 2015,
       2016], dtype=object)

In [ ]:
2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019

In [190]:
df[df['season'] == 2009]str

Empty DataFrame
Columns: [over_ball, batting_team, batsman_striker, batsman_non_striker, bowler, runs_scored, extra, dissmisal_type, batsman_out, match_venue, match_toss_winner, match_toss_decision, team_won, date, season, match_id]
Index: []

In [191]:
for value  in df.season.values()

,over_ball,batting_team,batsman_striker,batsman_non_striker,bowler,runs_scored,extra,dissmisal_type,batsman_out,match_venue,match_toss_winner,match_toss_decision,team_won,date,season,match_id
0,0.1,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591
1,0.2,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591
2,0.3,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,4,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591
3,0.4,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591
4,0.5,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,2,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591

In [183]:
df[df['batsman_striker']== ' DA Warner']

Empty DataFrame
Columns: [over_ball, batting_team, batsman_striker, batsman_non_striker, bowler, runs_scored, extra, dissmisal_type, batsman_out, match_venue, match_toss_winner, match_toss_decision, team_won, date, season, match_id]
Index: []

In [195]:
len(df.match_venue.unique())

28

In [200]:
season_2017= df_all_matches[df_all_matches['season']== 2017]

In [211]:
season_2017['ball'] = 1

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [232]:
season_2017['bat']=1

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [351]:
a= (season_2017.groupby(['batsman_striker','match_id']).sum())

In [352]:
a= a.reset_index()

In [353]:
a['innings']= 1

In [354]:
a.head()

  batsman_striker  match_id  over_ball  runs_scored  extra  ball  innings
0     A Choudhary   1082591       38.7            6      0     2        1
1     A Choudhary   1082621      210.9           15      0    12        1
2     A Choudhary   1082633      108.5            4      0     6        1
3        A Mishra   1082595      249.2            8      0    14        1
4        A Mishra   1082626      169.1            4      2    11        1

In [357]:
a = a.pivot_table(index='batsman_striker',values=['runs_scored','ball', 'innings'],aggfunc=sum).head(20)

In [359]:
a.head()

                 ball  innings  runs_scored
batsman_striker
A Choudhary        20        3           25
A Mishra           56        6           49
A Zampa             7        1            5
AB Dinda            8        1            7
AB de Villiers    171        9          216

In [ ]:
a.merge(outs, on="batsman_st")

In [251]:
season_2017.head()

,over_ball,batting_team,batsman_striker,batsman_non_striker,bowler,runs_scored,extra,dissmisal_type,batsman_out,match_venue,match_toss_winner,match_toss_decision,team_won,date,season,match_id,ball
0,0.1,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1
1,0.2,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1
2,0.3,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,4,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1
3,0.4,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1
4,0.5,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,2,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1

In [302]:
d = {}
l = []

In [287]:
for value in batsman_out_arr:
#   d[value]=1
    if value in season_2017.batsman_out.values:
        l.append(value)

In [333]:
for value in season_2017.batsman_out.values:
    if value not in d.keys():
        d[value]=1

    else:
        d[value]+=1
print(d)

{'DA Warner': 22, 'S Dhawan': 26, 'MC Henriques': 12, 'Yuvraj Singh': 18, 'Mandeep Singh': 20, 'CH Gayle': 18, 'KM Jadhav': 24, 'TM Head': 10, 'Sachin Baby': 6, 'STR Binny': 10, 'SR Watson': 12, 'S Aravind': 8, 'TS Mills': 6, 'YS Chahal': 6, 'PA Patel': 32, 'RG Sharma': 28, 'JC Buttler': 22, 'AT Rayudu': 10, 'KH Pandya': 16, 'N Rana': 22, 'KA Pollard': 28, 'TG Southee': 2, 'MA Agarwal': 6, 'AM Rahane': 30, 'BA Stokes': 20, 'JJ Roy': 4, 'BB McCullum': 22, 'AJ Finch': 24, 'KD Karthik': 20, 'SPD Smith': 24, 'MS Dhoni': 22, 'DT Christian': 10, 'M Vohra': 18, 'WP Saha': 20, 'HM Amla': 14, 'AR Patel': 16, 'Vishnu Vinod': 6, 'P Negi': 16, 'AP Tare': 6, 'KK Nair': 26, 'SW Billings': 12, 'SV Samson': 28, 'CH Morris': 10, 'CR Brathwaite': 4, 'PJ Cummins': 10, 'RR Pant': 28, 'S Nadeem': 6, 'SK Raina': 22, 'DR Smith': 22, 'DS Kulkarni': 2, 'G Gambhir': 24, 'RV Uthappa': 26, 'CA Lynn': 12, 'YK Pathan': 16, 'SA Yadav': 12, 'CR Woakes': 8, 'SP Narine': 26, 'RA Tripathi': 28, 'F du Plessis': 2, 'R Bhatia': 2, 'DL Chahar': 2, 'A Zampa': 2, 'AB Dinda': 2, 'DJ Hooda': 6, 'BCJ Cutting': 4, 'V Shankar': 4, 'NV Ojha': 8, 'Rashid Khan': 4, 'MP Stoinis': 6, 'GJ Maxwell': 20, 'DA Miller': 6, 'MM Sharma': 12, 'VR Aaron': 2, 'V Kohli': 20, 'AB de Villiers': 16, 'MJ McClenaghan': 8, 'Ankit Sharma': 2, 'MK Tiwary': 20, 'SN Thakur': 6, 'MK Pandey': 16, 'C de Grandhomme': 16, 'SS Iyer': 20, 'EJG Morgan': 8, 'KC Cariappa': 4, 'Ishan Kishan': 20, 'S Badree': 10, 'AF Milne': 4, 'AD Mathews': 4, 'Mohammad Nabi': 2, 'I Sharma': 4, 'RA Jadeja': 8, 'KS Williamson': 12, 'SE Marsh': 16, 'Harbhajan Singh': 4, 'HH Pandya': 14, 'CJ Anderson': 14, 'K Rabada': 6, 'AD Nath': 2, 'AJ Tye': 4, 'NM Coulter-Nile': 6, 'Kuldeep Yadav': 4, 'KV Sharma': 12, 'MJ Guptill': 12, 'Anureet Singh': 2, 'IK Pathan': 2, 'JP Faulkner': 8, 'JJ Bumrah': 2, 'Mohammed Shami': 8, 'SP Jackson': 4, 'PJ Sangwan': 4, 'Ankit Soni': 4, 'A Choudhary': 2, 'Bipul Sharma': 2, 'B Kumar': 2, 'LMP Simmons': 14, 'MN Samuels': 8, 'Z Khan': 2, 'Swapnil Singh': 4, 'P Kumar': 2, 'MM Patel': 2, 'SS Tiwary': 2, 'R Tewatia': 2, 'A Mishra': 2, 'CJ Jordan': 2, 'IR Jaggi': 2, 'PP Chawla': 2, 'AS Rajpoot': 2, 'Washington Sundar': 2, '""': 13151}

In [371]:
outs = pd.DataFrame.from_dict(d,orient='index',columns=['total_outs']).reset_index()

In [259]:
batsman_out_arr = season_2017.batsman_out.unique()

In [277]:
for key in d.keys():
    if key in season_2017.batsman_out.values:
        d[key]+=1

In [365]:
outs = (outs.reset_index())

In [373]:
outs.rename(columns={'index':'batsman_striker'}, inplace=True)

In [329]:
for key in d.keys():
    if key=='""':
        print (True)

True

In [335]:
a = d.pop('""')

KeyError: '""'

In [340]:
!ls

__pycache__           feature_extraction.py
cleaning_data.py      match_cleaning.ipynb

In [555]:
from feature_extraction import extracting_total_outs_per_batsman, runs_per_season, all_features

In [464]:
all_features(season_2017)

/Users/panesar47/galvanize/Performance-predictor-IPL/src/feature_extraction.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df['ball']=1

AttributeError: 'DataFrame' object has no attribute 'total_outs'

In [435]:
extracting_total_outs_per_batsman(season_2017)

       batsman_striker  total_outs
0                   ""       13151
1            DA Warner          11
2             S Dhawan          13
3         MC Henriques           6
4         Yuvraj Singh           9
5        Mandeep Singh          10
6             CH Gayle           9
7            KM Jadhav          12
8              TM Head           5
9          Sachin Baby           3
10           STR Binny           5
11           SR Watson           6
12           S Aravind           4
13            TS Mills           3
14           YS Chahal           3
15            PA Patel          16
16           RG Sharma          14
17          JC Buttler          11
18           AT Rayudu           5
19           KH Pandya           8
20              N Rana          11
21          KA Pollard          14
22          TG Southee           1
23          MA Agarwal           3
24           AM Rahane          15
25           BA Stokes          10
26              JJ Roy           2
27         BB McCullum          11
28            AJ Finch          12
29          KD Karthik          10
..                 ...         ...
99              AJ Tye           2
100    NM Coulter-Nile           3
101      Kuldeep Yadav           2
102          KV Sharma           6
103         MJ Guptill           6
104      Anureet Singh           1
105          IK Pathan           1
106        JP Faulkner           4
107          JJ Bumrah           1
108     Mohammed Shami           4
109         SP Jackson           2
110         PJ Sangwan           2
111         Ankit Soni           2
112        A Choudhary           1
113       Bipul Sharma           1
114            B Kumar           1
115        LMP Simmons           7
116         MN Samuels           4
117             Z Khan           1
118      Swapnil Singh           2
119            P Kumar           1
120           MM Patel           1
121          SS Tiwary           1
122          R Tewatia           1
123           A Mishra           1
124          CJ Jordan           1
125           IR Jaggi           1
126          PP Chawla           1
127         AS Rajpoot           1
128  Washington Sundar           1

[129 rows x 2 columns]

In [436]:
df

,over_ball,batting_team,batsman_striker,batsman_non_striker,bowler,runs_scored,extra,dissmisal_type,batsman_out,match_venue,match_toss_winner,match_toss_decision,team_won,date,season,match_id,ball,innings
0,0.1,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
1,0.2,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
2,0.3,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,4,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
3,0.4,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
4,0.5,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,2,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
5,0.6,Sunrisers Hyderabad,S Dhawan,DA Warner,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
6,0.7,Sunrisers Hyderabad,S Dhawan,DA Warner,TS Mills,0,1,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
7,1.1,Sunrisers Hyderabad,S Dhawan,DA Warner,A Choudhary,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
8,1.2,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,4,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
9,1.3,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,0,1,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
10,1.4,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,6,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
11,1.5,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,0,0,caught,DA Warner,"""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
12,1.6,Sunrisers Hyderabad,MC Henriques,S Dhawan,A Choudhary,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
13,1.7,Sunrisers Hyderabad,MC Henriques,S Dhawan,A Choudhary,4,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
14,2.1,Sunrisers Hyderabad,S Dhawan,MC Henriques,TS Mills,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
15,2.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
16,2.3,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
17,2.4,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,3,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
18,2.5,Sunrisers Hyderabad,S Dhawan,MC Henriques,TS Mills,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
19,2.6,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
20,3.1,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
21,3.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
22,3.3,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
23,3.4,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
24,3.5,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
25,3.6,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
26,4.1,Sunrisers Hyderabad,S Dhawan,MC Henriques,S Aravind,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
27,4.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,S Aravind,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
28,4.3,Sunrisers Hyderabad,S Dhawan,MC Henriques,S Aravind,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
29,4.4,Sunrisers Hyderabad,MC Henriques,S Dhawan,S Aravind,2,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,15.1,Royal Challengers Bangalore,KL Rahul,SR Watson,BCJ Cutting,1,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
221,15.2,Royal Challengers Bangalore,SR Watson,KL Rahul,BCJ Cutting,1,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
222,15.3,Royal Challengers Bangalore,KL Rahul,SR Watson,BCJ Cutting,0,0,bowled,KL Rahul,M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
223,15.4,Royal Challengers Bangalore,Sachin Baby,SR Watson,BCJ Cutting,0,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
224,15.5,Royal Challengers Bangalore,Sachin Baby,SR Watson,BCJ Cutting,1,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
225,15.6,Royal Challengers Bangalore,SR Watson,Sachin Baby,BCJ Cutting,1,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
226,16.1,Royal Challengers Bangalore,SR Watson,Sachin Baby,Mustafizur Rahman,0,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
227,16.2,Royal Challengers Bangalore,SR Watson,Sachin Baby,Mustafizur Rahman,2,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
228,16.3,Royal Challengers Bangalore,SR Watson,Sachin Baby,Mustafizur Rahman,0,0,caught,SR Watson,M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
229,16.4,Royal Challengers Bangalore,Sachin Baby,STR Binny,Mustafizur Rahman,1,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
230,16.5,Royal Challengers Bangalore,STR Binny,Sachin Baby,Mustafizur Rahman,6,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
231,16.6,Royal Challengers Bangalore,STR Binny,Sachin Baby,Mustafizur Rahman,1,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
232,17.1,Royal Challengers Bangalore,STR Binny,Sachin Baby,B Kumar,0,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
233,17.2,Royal Challengers Bangalore,STR Binny,Sachin Baby,B Kumar,1,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
234,17.3,Royal Challengers Bangalore,Sachin Baby,STR Binny,B Kumar,1,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
235,17.4,Royal Challengers Bangalore,STR Binny,Sachin Baby,B Kumar,0,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
236,17.5,Royal Challengers Bangalore,STR Binny,Sachin Baby,B Kumar,0,1,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
237,17.6,Royal Challengers Bangalore,Sachin Baby,STR Binny,B Kumar,4,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
238,18.1,Royal Challengers Bangalore,STR Binny,Sachin Baby,Mustafizur Rahman,1,0,run out,STR Binny,M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
239,18.2,Royal Challengers Bangalore,CJ Jordan,Sachin Baby,Mustafizur Rahman,2,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
240,18.3,Royal Challengers Bangalore,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
241,18.4,Royal Challengers Bangalore,CJ Jordan,Sachin Baby,Mustafizur Rahman,0,1,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
242,18.5,Royal Challengers Bangalore,Sachin Baby,CJ Jordan,Mustafizur Rahman,2,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
243,18.6,Royal Challengers Bangalore,Sachin Baby,CJ Jordan,Mustafizur Rahman,6,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
244,19.1,Royal Challengers Bangalore,CJ Jordan,Sachin Baby,B Kumar,1,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
245,19.2,Royal Challengers Bangalore,Sachin Baby,CJ Jordan,B Kumar,2,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
246,19.3,Royal Challengers Bangalore,Sachin Baby,CJ Jordan,B Kumar,0,0,run out,CJ Jordan,M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
247,19.4,Royal Challengers Bangalore,Iqbal Abdulla,Sachin Baby,B Kumar,0,1,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
248,19.5,Royal Challengers Bangalore,Sachin Baby,Iqbal Abdulla,B Kumar,1,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1
249,19.6,Royal Challengers Bangalore,Iqbal Abdulla,Sachin Baby,B Kumar,4,0,"""""","""""",M Chinnaswamy Stadium,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,2016/05/29,2016,981019,1,1

In [457]:
runs_per_season(season_2017)

/Users/panesar47/galvanize/Performance-predictor-IPL/src/feature_extraction.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df['ball']=1

       batsman_striker  ball  innings  runs_scored  total_outs
0          A Choudhary    20        3           25           1
1             A Mishra    56        6           49           1
2              A Zampa     7        1            5           1
3             AB Dinda     8        1            7           1
4       AB de Villiers   171        9          216           8
5           AD Mathews    28        2           32           2
6              AD Nath     1        1            0           1
7             AF Milne    12        3            7           2
8             AJ Finch   190       13          300          12
9               AJ Tye    30        3           53           2
10           AM Rahane   328       16          382          15
11             AP Tare    25        3           18           3
12            AR Patel   171       13          227           8
13          AS Rajpoot     7        1            4           1
14           AT Rayudu    80        5           91           5
15        Ankit Sharma    16        1           25           1
16          Ankit Soni     9        3            7           2
17       Anureet Singh    12        1           15           1
18             B Kumar     4        2            4           1
19           BA Stokes   227       11          316          10
20         BB McCullum   227       11          320          11
21         BCJ Cutting    27        3           51           2
22        Bipul Sharma    25        3           31           1
23     C de Grandhomme    92        9          126           8
24             CA Lynn   175        7          295           6
25            CH Gayle   172        9          200           9
26           CH Morris    97        8          154           5
27         CJ Anderson   130       11          142           7
28           CJ Jordan     1        1            0           1
29       CR Brathwaite    16        2           12           2
..                 ...   ...      ...          ...         ...
98            S Dhawan   383       14          479          13
99            S Nadeem     9        3            2           3
100           SA Yadav    89        7          105           6
101           SE Marsh   198        8          264           8
102           SK Raina   310       14          442          11
103          SN Thakur     3        3            0           3
104         SP Jackson    31        3           38           2
105          SP Narine   135       14          224          13
106          SPD Smith   400       15          472          12
107          SR Watson    80        7           71           6
108            SS Iyer   249       12          338          10
109          SS Tiwary    46        1           52           1
110          STR Binny    77        7           78           5
111          SV Samson   275       14          386          14
112        SW Billings   107        6          138           6
113        Sachin Baby    17        3           15           3
114      Swapnil Singh    19        2           12           2
115         TG Southee     3        1            7           1
116            TM Head   109        7          151           5
117           TS Mills    11        3            8           3
118            V Kohli   257       10          308          10
119          V Shankar    77        4          101           2
120           VR Aaron    11        2            4           1
121       Vishnu Vinod    26        3           19           3
122            WP Saha   194       11          234          10
123  Washington Sundar    12        5            9           1
124          YK Pathan   123       11          143           8
125          YS Chahal    26        6           13           3
126       Yuvraj Singh   188       11          252           9
127             Z Khan    13        3            4           1

[128 rows x 5 columns]

In [386]:
extracting_total_outs_per_batsman(season_2017)

       batsman_striker  total_outs
0                   ""       13151
1            DA Warner          11
2             S Dhawan          13
3         MC Henriques           6
4         Yuvraj Singh           9
5        Mandeep Singh          10
6             CH Gayle           9
7            KM Jadhav          12
8              TM Head           5
9          Sachin Baby           3
10           STR Binny           5
11           SR Watson           6
12           S Aravind           4
13            TS Mills           3
14           YS Chahal           3
15            PA Patel          16
16           RG Sharma          14
17          JC Buttler          11
18           AT Rayudu           5
19           KH Pandya           8
20              N Rana          11
21          KA Pollard          14
22          TG Southee           1
23          MA Agarwal           3
24           AM Rahane          15
25           BA Stokes          10
26              JJ Roy           2
27         BB McCullum          11
28            AJ Finch          12
29          KD Karthik          10
..                 ...         ...
99              AJ Tye           2
100    NM Coulter-Nile           3
101      Kuldeep Yadav           2
102          KV Sharma           6
103         MJ Guptill           6
104      Anureet Singh           1
105          IK Pathan           1
106        JP Faulkner           4
107          JJ Bumrah           1
108     Mohammed Shami           4
109         SP Jackson           2
110         PJ Sangwan           2
111         Ankit Soni           2
112        A Choudhary           1
113       Bipul Sharma           1
114            B Kumar           1
115        LMP Simmons           7
116         MN Samuels           4
117             Z Khan           1
118      Swapnil Singh           2
119            P Kumar           1
120           MM Patel           1
121          SS Tiwary           1
122          R Tewatia           1
123           A Mishra           1
124          CJ Jordan           1
125           IR Jaggi           1
126          PP Chawla           1
127         AS Rajpoot           1
128  Washington Sundar           1

[129 rows x 2 columns]

In [390]:
a = a.reset_index()

In [445]:
outs[['bas', 'inings']]=1,1
outs

KeyError: "['bas' 'inings'] not in index"

In [446]:
a = a.merge(outs, on= 'batsman_striker')

In [448]:
a.drop('balls', axis = 1, inplace=True)

In [455]:
a['Average'] = round(a.runs_scored / a.total_outs,2)

In [460]:
a['strike_rate'] = round((a.runs_scored/a.ball)*100,2)

In [468]:
ok = all_features(season_2017)

/Users/panesar47/galvanize/Performance-predictor-IPL/src/feature_extraction.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df['ball']=1

In [535]:
ok.sort_values('runs_scored', ascending=False)

,batsman_striker,ball,innings,runs_scored,total_outs,Average,strike_rate
32,DA Warner,462,14,641,11,58.27,138.74
40,G Gambhir,405,16,498,12,41.50,122.96
98,S Dhawan,383,14,479,13,36.85,125.07
106,SPD Smith,400,15,472,12,39.33,118.00
102,SK Raina,310,14,442,11,40.18,142.58
43,HM Amla,296,10,420,7,60.00,141.89
69,MK Pandey,315,12,396,8,49.50,125.71
84,PA Patel,308,16,395,16,24.69,128.25
54,KA Pollard,294,16,395,14,28.21,134.35
91,RA Tripathi,275,14,391,14,27.93,142.18
94,RV Uthappa,239,13,388,13,29.85,162.34
111,SV Samson,275,14,386,14,27.57,140.36
10,AM Rahane,328,16,382,15,25.47,116.46
93,RR Pant,226,14,366,14,26.14,161.95
56,KD Karthik,268,13,361,10,36.10,134.70
108,SS Iyer,249,12,338,10,33.80,135.74
92,RG Sharma,278,16,333,14,23.79,119.78
79,N Rana,277,12,333,11,30.27,120.22
70,MK Tiwary,242,13,324,10,32.40,133.88
20,BB McCullum,227,11,320,11,29.09,140.97
19,BA Stokes,227,11,316,10,31.60,139.21
41,GJ Maxwell,186,13,310,10,31.00,166.67
118,V Kohli,257,10,308,10,30.80,119.84
8,AJ Finch,190,13,300,12,25.00,157.89
24,CA Lynn,175,7,295,6,49.17,168.57
75,MS Dhoni,261,15,290,11,26.36,111.11
58,KK Nair,229,13,281,13,21.62,122.71
66,MC Henriques,205,11,277,6,46.17,135.12
48,Ishan Kishan,214,10,277,10,27.70,129.44
49,JC Buttler,186,10,273,11,24.82,146.77
...,...,...,...,...,...,...,...
97,S Badree,25,5,13,5,2.60,52.00
125,YS Chahal,26,6,13,3,4.33,50.00
114,Swapnil Singh,19,2,12,2,6.00,63.16
29,CR Brathwaite,16,2,12,2,6.00,75.00
95,Rashid Khan,9,3,11,2,5.50,122.22
123,Washington Sundar,12,5,9,1,9.00,75.00
117,TS Mills,11,3,8,3,2.67,72.73
82,P Kumar,9,2,8,1,8.00,88.89
45,I Sharma,13,3,8,2,4.00,61.54
39,F du Plessis,7,1,8,1,8.00,114.29
16,Ankit Soni,9,3,7,2,3.50,77.78
3,AB Dinda,8,1,7,1,7.00,87.50
115,TG Southee,3,1,7,1,7.00,233.33
7,AF Milne,12,3,7,2,3.50,58.33
2,A Zampa,7,1,5,1,5.00,71.43
127,Z Khan,13,3,4,1,4.00,30.77
120,VR Aaron,11,2,4,1,4.00,36.36
18,B Kumar,4,2,4,1,4.00,100.00
13,AS Rajpoot,7,1,4,1,4.00,57.14
86,PJ Sangwan,4,3,2,2,1.00,50.00
87,PP Chawla,6,1,2,1,2.00,33.33
77,Mohammad Nabi,3,1,2,1,2.00,66.67
55,KC Cariappa,7,2,2,2,1.00,28.57
99,S Nadeem,9,3,2,3,0.67,22.22
46,IK Pathan,3,1,2,1,2.00,66.67
36,DS Kulkarni,2,1,1,1,1.00,50.00
71,MM Patel,1,1,0,1,0.00,0.00
6,AD Nath,1,1,0,1,0.00,0.00
103,SN Thakur,3,3,0,3,0.00,0.00
28,CJ Jordan,1,1,0,1,0.00,0.00

In [483]:
df_all_matches.season.unique()

array([2017, '2007/08', 2009, '2009/10', 2011, 2012, 2013, 2014, 2015,
       2016], dtype=object)

In [485]:
s = df_all_matches.season.iloc[0]

In [492]:
s = []

In [506]:
test = df_all_matches

In [508]:
type(test.season.iloc[0])

str

In [507]:
test['season'] = test['season'].astype(str)

In [511]:
kl = test.match_venue.unique()

In [524]:
f.lstrip('"')

'Rajiv Gandhi International Stadium'

In [530]:
a = []
for value in test['match_venue'].values:
    if value[0] =='"':
        value = value.lstrip('"')
        a.append(value)
    else:
        a.append(value)
        pass

In [532]:
test['match_venue'] = a

In [534]:
test.match_venue.unique()

array(['Rajiv Gandhi International Stadium',
       'Maharashtra Cricket Association Stadium',
       'Saurashtra Cricket Association Stadium', 'Holkar Cricket Stadium',
       'M Chinnaswamy Stadium', 'Wankhede Stadium', 'Eden Gardens',
       'Feroz Shah Kotla', 'Punjab Cricket Association IS Bindra Stadium',
       'Green Park', 'Punjab Cricket Association Stadium',
       'Sawai Mansingh Stadium', 'MA Chidambaram Stadium',
       'Dr DY Patil Sports Academy', 'Newlands', "St George's Park",
       'Kingsmead', 'SuperSport Park', 'Buffalo Park',
       'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium', 'Sardar Patel Stadium',
       'Barabati Stadium', 'Vidarbha Cricket Association Stadium',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium'],
      dtype=object)

In [527]:
test['match_venue'] =

'"'

In [518]:
f = '"Rajiv Gandhi International Stadium'

In [509]:
test.season.unique()

array(['2017', '2007/08', '2009', '2009/10', '2011', '2012', '2013',
       '2014', '2015', '2016'], dtype=object)

In [493]:
for value in df_all_matches.season.values:
    if type(value) == str:
        pass
    else:
        s.append(str(value))

In [494]:
s

['2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 ...]

In [473]:
ok.sort_values('strike_rate', ascending=False)

,batsman_striker,ball,innings,runs_scored,total_outs,Average,strike_rate
34,DL Chahar,6,1,14,1,14.00,233.33
115,TG Southee,3,1,7,1,7.00,233.33
21,BCJ Cutting,27,3,51,2,25.50,188.89
9,AJ Tye,30,3,53,2,26.50,176.67
89,R Tewatia,11,2,19,1,19.00,172.73
24,CA Lynn,175,7,295,6,49.17,168.57
41,GJ Maxwell,186,13,310,10,31.00,166.67
105,SP Narine,135,14,224,13,17.23,165.93
94,RV Uthappa,239,13,388,13,29.85,162.34
93,RR Pant,226,14,366,14,26.14,161.95
26,CH Morris,97,8,154,5,30.80,158.76
8,AJ Finch,190,13,300,12,25.00,157.89
15,Ankit Sharma,16,1,25,1,25.00,156.25
37,DT Christian,52,9,79,5,15.80,151.92
35,DR Smith,158,11,239,11,21.73,151.27
60,KS Williamson,170,7,256,6,42.67,150.59
67,MJ Guptill,88,7,132,6,22.00,150.00
78,Mohammed Shami,24,6,36,4,9.00,150.00
33,DJ Hooda,53,6,78,3,26.00,147.17
49,JC Buttler,186,10,273,11,24.82,146.77
42,HH Pandya,172,16,250,7,35.71,145.35
51,JJ Roy,41,3,59,2,29.50,143.90
85,PJ Cummins,54,8,77,5,15.40,142.59
102,SK Raina,310,14,442,11,40.18,142.58
91,RA Tripathi,275,14,391,14,27.93,142.18
43,HM Amla,296,10,420,7,60.00,141.89
20,BB McCullum,227,11,320,11,29.09,140.97
111,SV Samson,275,14,386,14,27.57,140.36
19,BA Stokes,227,11,316,10,31.60,139.21
32,DA Warner,462,14,641,11,58.27,138.74
...,...,...,...,...,...,...,...
47,IR Jaggi,40,2,33,1,33.00,82.50
53,K Rabada,68,3,55,3,18.33,80.88
96,S Aravind,40,6,32,4,8.00,80.00
16,Ankit Soni,9,3,7,2,3.50,77.78
29,CR Brathwaite,16,2,12,2,6.00,75.00
123,Washington Sundar,12,5,9,1,9.00,75.00
121,Vishnu Vinod,26,3,19,3,6.33,73.08
117,TS Mills,11,3,8,3,2.67,72.73
11,AP Tare,25,3,18,3,6.00,72.00
2,A Zampa,7,1,5,1,5.00,71.43
74,MP Stoinis,25,3,17,3,5.67,68.00
77,Mohammad Nabi,3,1,2,1,2.00,66.67
46,IK Pathan,3,1,2,1,2.00,66.67
114,Swapnil Singh,19,2,12,2,6.00,63.16
45,I Sharma,13,3,8,2,4.00,61.54
7,AF Milne,12,3,7,2,3.50,58.33
13,AS Rajpoot,7,1,4,1,4.00,57.14
97,S Badree,25,5,13,5,2.60,52.00
86,PJ Sangwan,4,3,2,2,1.00,50.00
36,DS Kulkarni,2,1,1,1,1.00,50.00
125,YS Chahal,26,6,13,3,4.33,50.00
120,VR Aaron,11,2,4,1,4.00,36.36
87,PP Chawla,6,1,2,1,2.00,33.33
127,Z Khan,13,3,4,1,4.00,30.77
55,KC Cariappa,7,2,2,2,1.00,28.57
99,S Nadeem,9,3,2,3,0.67,22.22
71,MM Patel,1,1,0,1,0.00,0.00
6,AD Nath,1,1,0,1,0.00,0.00
28,CJ Jordan,1,1,0,1,0.00,0.00
103,SN Thakur,3,3,0,3,0.00,0.00

In [476]:
al  = all_features(df_all_matches)

In [478]:
al.sort_values('runs_scored', ascending = False)

,batsman_striker,ball,innings,runs_scored,total_outs,Average,strike_rate
352,SK Raina,3369,157,4548,134,33.94,135.00
406,V Kohli,3494,141,4423,118,37.48,126.59
303,RG Sharma,3274,153,4207,129,32.61,128.50
128,G Gambhir,3433,146,4132,131,31.54,120.36
97,DA Warner,2902,114,4014,100,40.14,138.32
319,RV Uthappa,2960,143,3778,128,29.52,127.64
80,CH Gayle,2532,100,3651,89,41.02,144.19
326,S Dhawan,3005,126,3561,109,32.67,118.50
245,MS Dhoni,2680,143,3560,94,37.87,132.84
21,AB de Villiers,2402,118,3486,91,38.31,145.13
37,AM Rahane,2602,105,3057,91,33.59,117.49
428,YK Pathan,2076,133,2922,98,29.82,140.75
184,KD Karthik,2360,134,2903,117,24.81,123.01
63,BB McCullum,2181,103,2755,98,28.11,126.32
408,V Sehwag,1833,104,2728,99,27.56,148.83
367,SR Watson,1949,98,2628,85,30.92,134.84
433,Yuvraj Singh,2050,116,2591,101,25.65,126.39
218,M Vijay,2092,99,2511,95,26.43,120.03
350,SE Marsh,1913,69,2489,63,39.51,130.11
166,JH Kallis,2291,95,2427,85,28.55,105.94
47,AT Rayudu,1964,105,2416,89,27.15,123.01
116,DR Smith,1803,88,2385,84,28.39,132.28
179,KA Pollard,1674,112,2354,82,28.71,140.62
366,SR Tendulkar,2044,78,2334,69,33.83,114.19
272,PA Patel,2060,116,2322,107,21.70,112.72
235,MK Pandey,1901,95,2223,78,28.50,116.94
290,R Dravid,1918,82,2174,77,28.23,113.35
23,AC Gilchrist,1555,80,2069,76,27.22,133.05
172,JP Duminy,1634,73,1993,50,39.86,121.97
228,MEK Hussey,1648,58,1977,51,38.76,119.96
...,...,...,...,...,...,...,...
164,JE Taylor,4,2,3,1,3.00,75.00
62,BAW Mendis,6,3,3,2,1.50,50.00
252,Mohammad Asif,6,2,3,2,1.50,50.00
337,S Tyagi,4,1,3,1,3.00,75.00
292,R Ninan,6,1,3,1,3.00,50.00
92,D Kalyankrishna,8,1,3,1,3.00,37.50
9,A Singh,10,5,2,4,0.50,20.00
191,KP Appanna,4,3,2,1,2.00,50.00
251,Mohammad Ashraful,12,1,2,1,2.00,16.67
254,Mohammad Nabi,3,1,2,1,2.00,66.67
137,H Das,5,1,2,1,2.00,40.00
383,Shoaib Akhtar,8,1,2,1,2.00,25.00
316,RS Gavaskar,8,1,2,1,2.00,25.00
414,VS Yeligati,2,1,2,1,2.00,100.00
333,S Randiv,4,1,2,1,2.00,50.00
346,SB Wagh,3,2,2,2,1.00,66.67
66,BE Hendricks,3,2,1,1,1.00,33.33
382,Shoaib Ahmed,6,3,1,2,0.50,16.67
107,DJ Muthuswami,3,1,1,1,1.00,33.33
220,M de Lange,2,1,1,1,1.00,50.00
349,SE Bond,2,1,1,1,1.00,50.00
146,IC Pandey,2,1,0,1,0.00,0.00
209,M Ashwin,1,1,0,1,0.00,0.00
407,V Pratap Singh,1,1,0,1,0.00,0.00
75,C Nanda,1,1,0,1,0.00,0.00
328,S Kaushik,1,1,0,1,0.00,0.00
258,ND Doshi,13,1,0,1,0.00,0.00
329,S Ladda,10,2,0,1,0.00,0.00
309,RR Bhatkal,2,1,0,1,0.00,0.00
386,Sunny Gupta,1,1,0,1,0.00,0.00

In [537]:
jk = all_features(df_all_matches)

In [539]:
jk.sort_values('runs_scored', ascending=False)

,batsman_striker,ball,innings,runs_scored,total_outs,Average,strike_rate
352,SK Raina,3369,157,4548,134,33.94,135.00
406,V Kohli,3494,141,4423,118,37.48,126.59
303,RG Sharma,3274,153,4207,129,32.61,128.50
128,G Gambhir,3433,146,4132,131,31.54,120.36
97,DA Warner,2902,114,4014,100,40.14,138.32
319,RV Uthappa,2960,143,3778,128,29.52,127.64
80,CH Gayle,2532,100,3651,89,41.02,144.19
326,S Dhawan,3005,126,3561,109,32.67,118.50
245,MS Dhoni,2680,143,3560,94,37.87,132.84
21,AB de Villiers,2402,118,3486,91,38.31,145.13
37,AM Rahane,2602,105,3057,91,33.59,117.49
428,YK Pathan,2076,133,2922,98,29.82,140.75
184,KD Karthik,2360,134,2903,117,24.81,123.01
63,BB McCullum,2181,103,2755,98,28.11,126.32
408,V Sehwag,1833,104,2728,99,27.56,148.83
367,SR Watson,1949,98,2628,85,30.92,134.84
433,Yuvraj Singh,2050,116,2591,101,25.65,126.39
218,M Vijay,2092,99,2511,95,26.43,120.03
350,SE Marsh,1913,69,2489,63,39.51,130.11
166,JH Kallis,2291,95,2427,85,28.55,105.94
47,AT Rayudu,1964,105,2416,89,27.15,123.01
116,DR Smith,1803,88,2385,84,28.39,132.28
179,KA Pollard,1674,112,2354,82,28.71,140.62
366,SR Tendulkar,2044,78,2334,69,33.83,114.19
272,PA Patel,2060,116,2322,107,21.70,112.72
235,MK Pandey,1901,95,2223,78,28.50,116.94
290,R Dravid,1918,82,2174,77,28.23,113.35
23,AC Gilchrist,1555,80,2069,76,27.22,133.05
172,JP Duminy,1634,73,1993,50,39.86,121.97
228,MEK Hussey,1648,58,1977,51,38.76,119.96
...,...,...,...,...,...,...,...
164,JE Taylor,4,2,3,1,3.00,75.00
62,BAW Mendis,6,3,3,2,1.50,50.00
252,Mohammad Asif,6,2,3,2,1.50,50.00
337,S Tyagi,4,1,3,1,3.00,75.00
292,R Ninan,6,1,3,1,3.00,50.00
92,D Kalyankrishna,8,1,3,1,3.00,37.50
9,A Singh,10,5,2,4,0.50,20.00
191,KP Appanna,4,3,2,1,2.00,50.00
251,Mohammad Ashraful,12,1,2,1,2.00,16.67
254,Mohammad Nabi,3,1,2,1,2.00,66.67
137,H Das,5,1,2,1,2.00,40.00
383,Shoaib Akhtar,8,1,2,1,2.00,25.00
316,RS Gavaskar,8,1,2,1,2.00,25.00
414,VS Yeligati,2,1,2,1,2.00,100.00
333,S Randiv,4,1,2,1,2.00,50.00
346,SB Wagh,3,2,2,2,1.00,66.67
66,BE Hendricks,3,2,1,1,1.00,33.33
382,Shoaib Ahmed,6,3,1,2,0.50,16.67
107,DJ Muthuswami,3,1,1,1,1.00,33.33
220,M de Lange,2,1,1,1,1.00,50.00
349,SE Bond,2,1,1,1,1.00,50.00
146,IC Pandey,2,1,0,1,0.00,0.00
209,M Ashwin,1,1,0,1,0.00,0.00
407,V Pratap Singh,1,1,0,1,0.00,0.00
75,C Nanda,1,1,0,1,0.00,0.00
328,S Kaushik,1,1,0,1,0.00,0.00
258,ND Doshi,13,1,0,1,0.00,0.00
329,S Ladda,10,2,0,1,0.00,0.00
309,RR Bhatkal,2,1,0,1,0.00,0.00
386,Sunny Gupta,1,1,0,1,0.00,0.00

In [542]:
new = df_all_matches[df_all_matches['season']=='2017']

In [543]:
new.head()

,over_ball,batting_team,batsman_striker,batsman_non_striker,bowler,runs_scored,extra,dissmisal_type,batsman_out,match_venue,match_toss_winner,match_toss_decision,team_won,date,season,match_id,ball
0,0.1,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""",Rajiv Gandhi International Stadium,Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1
1,0.2,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""",Rajiv Gandhi International Stadium,Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1
2,0.3,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,4,0,"""""","""""",Rajiv Gandhi International Stadium,Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1
3,0.4,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""",Rajiv Gandhi International Stadium,Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1
4,0.5,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,2,"""""","""""",Rajiv Gandhi International Stadium,Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1

In [547]:
new_1 = new.groupby(['batsman_striker', 'match_id']).sum()

In [553]:
new_1.head()

                          over_ball  runs_scored  extra  ball
batsman_striker match_id
A Choudhary     1082591        38.7            6      0     2
                1082621       210.9           15      0    12
                1082633       108.5            4      0     6
A Mishra        1082595       249.2            8      0    14
                1082626       169.1            4      2    11

In [554]:
new_1.pivot_table(index='batsman_striker',values=['runs_scored', 'ball'],aggfunc=[sum,max])

                   sum              max
                  ball runs_scored ball runs_scored
batsman_striker
A Choudhary         20          25   12          15
A Mishra            56          49   15          13
A Zampa              7           5    7           5
AB Dinda             8           7    8           7
AB de Villiers     171         216   49          89
AD Mathews          28          32   24          31
AD Nath              1           0    1           0
AF Milne            12           7    8           5
AJ Finch           190         300   40          72
AJ Tye              30          53   12          25
AM Rahane          328         382   44          60
AP Tare             25          18   18          18
AR Bawne            12          12   12          12
AR Patel           171         227   29          44
AS Rajpoot           7           4    7           4
AT Rayudu           80          91   37          63
Ankit Sharma        16          25   16          25
Ankit Soni           9           7    6           7
Anureet Singh       12          15   12          15
B Kumar              4           4    3           4
BA Stokes          227         316   64         103
BB McCullum        227         320   48          72
BCJ Cutting         27          51   11          20
Basil Thampi        30          28   12          13
Bipul Sharma        25          31   14          21
C de Grandhomme     92         126   28          36
CA Lynn            175         295   54          93
CH Gayle           172         200   40          77
CH Morris           97         154   42          52
CJ Anderson        130         142   26          41
...                ...         ...  ...         ...
SL Malinga           3           7    2           7
SN Thakur            3           0    1           0
SP Jackson          31          38   17          16
SP Narine          135         224   19          54
SPD Smith          400         472   55          84
SR Watson           80          71   25          24
SS Iyer            249         338   57          96
SS Tiwary           46          52   46          52
STR Binny           77          78   20          18
SV Samson          275         386   64         102
SW Billings        107         138   41          55
Sachin Baby         17          15   10          12
Sandeep Sharma       7           7    5           5
Shakib Al Hasan      1           1    1           1
Swapnil Singh       19          12   17          10
TA Boult             8           5    8           5
TG Southee           3           7    3           7
TM Head            109         151   48          75
TS Mills            11           8    5           6
UT Yadav            13          10    4           4
V Kohli            257         308   51          64
V Shankar           77         101   44          63
VR Aaron            11           4    6           4
Vishnu Vinod        26          19   12           9
WP Saha            194         234   59          93
Washington Sundar   12           9    3           5
YK Pathan          123         143   40          59
YS Chahal           26          13    9           4
Yuvraj Singh       188         252   44          70
Z Khan              13           4   11           2

[143 rows x 4 columns]

In [557]:
all_features(df_all_matches)

AttributeError: 'DataFrame' object has no attribute 'runs_scored'

In [585]:
def runs_per_season_trail(df):
    #df_1 = extracting_total_outs_per_batsman(df)
    df['ball']=1
    df= (df.groupby(['batsman_striker','match_id']).sum()).reset_index()
    df['innings']=1
    df_sum = df.pivot_table(index='batsman_striker',values=['runs_scored', 'innings', 'ball'],aggfunc=sum)
    df_sum= df_sum.reset_index()
    df_max = df.pivot_table(index='batsman_striker',values=['runs_scored'],aggfunc=max)
    df_max = df_max.reset_index()
    df_sum = df_sum.merge(a, on ='batsman_striker').merge(df_max, on='batsman_striker')
    return df_sum

In [593]:
a = runs_per_season(season_2017)

/Users/panesar47/galvanize/Performance-predictor-IPL/src/feature_extraction.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df['ball']=1

In [594]:
a.head()

  batsman_striker  ball  innings  runs_scored_x  total_outs  highest_score
0     A Choudhary    20        3             25           1             15
1        A Mishra    56        6             49           1             13
2         A Zampa     7        1              5           1              5
3        AB Dinda     8        1              7           1              7
4  AB de Villiers   171        9            216           8             89

In [587]:
ad = runs_per_season_trail(df_all_matches)

In [588]:
ad.head()

  batsman_striker  ball  innings  runs_scored_x  total_outs  runs_scored_y
0  A Ashish Reddy   196       23            280          15             36
1        A Chopra    75        6             53           6             24
2     A Choudhary    20        3             25           1             15
3      A Flintoff    57        3             62           2             24
4        A Kumble    49       15             35           3              8

In [596]:
runs_per_season(season_2017)

/Users/panesar47/galvanize/Performance-predictor-IPL/src/feature_extraction.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df['ball']=1

,batsman_striker,ball,innings,runs_scored_x,total_outs,highest_score
0,A Choudhary,20,3,25,1,15
1,A Mishra,56,6,49,1,13
2,A Zampa,7,1,5,1,5
3,AB Dinda,8,1,7,1,7
4,AB de Villiers,171,9,216,8,89
5,AD Mathews,28,2,32,2,31
6,AD Nath,1,1,0,1,0
7,AF Milne,12,3,7,2,5
8,AJ Finch,190,13,300,12,72
9,AJ Tye,30,3,53,2,25
10,AM Rahane,328,16,382,15,60
11,AP Tare,25,3,18,3,18
12,AR Patel,171,13,227,8,44
13,AS Rajpoot,7,1,4,1,4
14,AT Rayudu,80,5,91,5,63
15,Ankit Sharma,16,1,25,1,25
16,Ankit Soni,9,3,7,2,7
17,Anureet Singh,12,1,15,1,15
18,B Kumar,4,2,4,1,4
19,BA Stokes,227,11,316,10,103
20,BB McCullum,227,11,320,11,72
21,BCJ Cutting,27,3,51,2,20
22,Bipul Sharma,25,3,31,1,21
23,C de Grandhomme,92,9,126,8,36
24,CA Lynn,175,7,295,6,93
25,CH Gayle,172,9,200,9,77
26,CH Morris,97,8,154,5,52
27,CJ Anderson,130,11,142,7,41
28,CJ Jordan,1,1,0,1,0
29,CR Brathwaite,16,2,12,2,11
...,...,...,...,...,...,...
98,S Dhawan,383,14,479,13,77
99,S Nadeem,9,3,2,3,2
100,SA Yadav,89,7,105,6,31
101,SE Marsh,198,8,264,8,84
102,SK Raina,310,14,442,11,84
103,SN Thakur,3,3,0,3,0
104,SP Jackson,31,3,38,2,16
105,SP Narine,135,14,224,13,54
106,SPD Smith,400,15,472,12,84
107,SR Watson,80,7,71,6,24
108,SS Iyer,249,12,338,10,96
109,SS Tiwary,46,1,52,1,52
110,STR Binny,77,7,78,5,18
111,SV Samson,275,14,386,14,102
112,SW Billings,107,6,138,6,55
113,Sachin Baby,17,3,15,3,12
114,Swapnil Singh,19,2,12,2,10
115,TG Southee,3,1,7,1,7
116,TM Head,109,7,151,5,75
117,TS Mills,11,3,8,3,6
118,V Kohli,257,10,308,10,64
119,V Shankar,77,4,101,2,63
120,VR Aaron,11,2,4,1,4
121,Vishnu Vinod,26,3,19,3,9
122,WP Saha,194,11,234,10,93
123,Washington Sundar,12,5,9,1,5
124,YK Pathan,123,11,143,8,59
125,YS Chahal,26,6,13,3,4
126,Yuvraj Singh,188,11,252,9,70
127,Z Khan,13,3,4,1,2

In [597]:
all_features(season_2017)

/Users/panesar47/galvanize/Performance-predictor-IPL/src/feature_extraction.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df['ball']=1

,batsman_striker,ball,innings,runs_scored,total_outs,highest_score,Average,strike_rate
0,A Choudhary,20,3,25,1,15,25.00,125.00
1,A Mishra,56,6,49,1,13,49.00,87.50
2,A Zampa,7,1,5,1,5,5.00,71.43
3,AB Dinda,8,1,7,1,7,7.00,87.50
4,AB de Villiers,171,9,216,8,89,27.00,126.32
5,AD Mathews,28,2,32,2,31,16.00,114.29
6,AD Nath,1,1,0,1,0,0.00,0.00
7,AF Milne,12,3,7,2,5,3.50,58.33
8,AJ Finch,190,13,300,12,72,25.00,157.89
9,AJ Tye,30,3,53,2,25,26.50,176.67
10,AM Rahane,328,16,382,15,60,25.47,116.46
11,AP Tare,25,3,18,3,18,6.00,72.00
12,AR Patel,171,13,227,8,44,28.38,132.75
13,AS Rajpoot,7,1,4,1,4,4.00,57.14
14,AT Rayudu,80,5,91,5,63,18.20,113.75
15,Ankit Sharma,16,1,25,1,25,25.00,156.25
16,Ankit Soni,9,3,7,2,7,3.50,77.78
17,Anureet Singh,12,1,15,1,15,15.00,125.00
18,B Kumar,4,2,4,1,4,4.00,100.00
19,BA Stokes,227,11,316,10,103,31.60,139.21
20,BB McCullum,227,11,320,11,72,29.09,140.97
21,BCJ Cutting,27,3,51,2,20,25.50,188.89
22,Bipul Sharma,25,3,31,1,21,31.00,124.00
23,C de Grandhomme,92,9,126,8,36,15.75,136.96
24,CA Lynn,175,7,295,6,93,49.17,168.57
25,CH Gayle,172,9,200,9,77,22.22,116.28
26,CH Morris,97,8,154,5,52,30.80,158.76
27,CJ Anderson,130,11,142,7,41,20.29,109.23
28,CJ Jordan,1,1,0,1,0,0.00,0.00
29,CR Brathwaite,16,2,12,2,11,6.00,75.00
...,...,...,...,...,...,...,...,...
98,S Dhawan,383,14,479,13,77,36.85,125.07
99,S Nadeem,9,3,2,3,2,0.67,22.22
100,SA Yadav,89,7,105,6,31,17.50,117.98
101,SE Marsh,198,8,264,8,84,33.00,133.33
102,SK Raina,310,14,442,11,84,40.18,142.58
103,SN Thakur,3,3,0,3,0,0.00,0.00
104,SP Jackson,31,3,38,2,16,19.00,122.58
105,SP Narine,135,14,224,13,54,17.23,165.93
106,SPD Smith,400,15,472,12,84,39.33,118.00
107,SR Watson,80,7,71,6,24,11.83,88.75
108,SS Iyer,249,12,338,10,96,33.80,135.74
109,SS Tiwary,46,1,52,1,52,52.00,113.04
110,STR Binny,77,7,78,5,18,15.60,101.30
111,SV Samson,275,14,386,14,102,27.57,140.36
112,SW Billings,107,6,138,6,55,23.00,128.97
113,Sachin Baby,17,3,15,3,12,5.00,88.24
114,Swapnil Singh,19,2,12,2,10,6.00,63.16
115,TG Southee,3,1,7,1,7,7.00,233.33
116,TM Head,109,7,151,5,75,30.20,138.53
117,TS Mills,11,3,8,3,6,2.67,72.73
118,V Kohli,257,10,308,10,64,30.80,119.84
119,V Shankar,77,4,101,2,63,50.50,131.17
120,VR Aaron,11,2,4,1,4,4.00,36.36
121,Vishnu Vinod,26,3,19,3,9,6.33,73.08
122,WP Saha,194,11,234,10,93,23.40,120.62
123,Washington Sundar,12,5,9,1,5,9.00,75.00
124,YK Pathan,123,11,143,8,59,17.88,116.26
125,YS Chahal,26,6,13,3,4,4.33,50.00
126,Yuvraj Singh,188,11,252,9,70,28.00,134.04
127,Z Khan,13,3,4,1,2,4.00,30.77

In [598]:
season_2017

,over_ball,batting_team,batsman_striker,batsman_non_striker,bowler,runs_scored,extra,dissmisal_type,batsman_out,match_venue,match_toss_winner,match_toss_decision,team_won,date,season,match_id,ball,innings
0,0.1,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
1,0.2,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
2,0.3,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,4,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
3,0.4,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
4,0.5,Sunrisers Hyderabad,DA Warner,S Dhawan,TS Mills,0,2,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
5,0.6,Sunrisers Hyderabad,S Dhawan,DA Warner,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
6,0.7,Sunrisers Hyderabad,S Dhawan,DA Warner,TS Mills,0,1,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
7,1.1,Sunrisers Hyderabad,S Dhawan,DA Warner,A Choudhary,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
8,1.2,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,4,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
9,1.3,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,0,1,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
10,1.4,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,6,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
11,1.5,Sunrisers Hyderabad,DA Warner,S Dhawan,A Choudhary,0,0,caught,DA Warner,"""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
12,1.6,Sunrisers Hyderabad,MC Henriques,S Dhawan,A Choudhary,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
13,1.7,Sunrisers Hyderabad,MC Henriques,S Dhawan,A Choudhary,4,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
14,2.1,Sunrisers Hyderabad,S Dhawan,MC Henriques,TS Mills,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
15,2.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
16,2.3,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
17,2.4,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,3,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
18,2.5,Sunrisers Hyderabad,S Dhawan,MC Henriques,TS Mills,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
19,2.6,Sunrisers Hyderabad,MC Henriques,S Dhawan,TS Mills,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
20,3.1,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
21,3.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
22,3.3,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
23,3.4,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
24,3.5,Sunrisers Hyderabad,MC Henriques,S Dhawan,YS Chahal,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
25,3.6,Sunrisers Hyderabad,S Dhawan,MC Henriques,YS Chahal,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
26,4.1,Sunrisers Hyderabad,S Dhawan,MC Henriques,S Aravind,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
27,4.2,Sunrisers Hyderabad,MC Henriques,S Dhawan,S Aravind,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
28,4.3,Sunrisers Hyderabad,S Dhawan,MC Henriques,S Aravind,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
29,4.4,Sunrisers Hyderabad,MC Henriques,S Dhawan,S Aravind,2,0,"""""","""""","""Rajiv Gandhi International Stadium",Royal Challengers Bangalore,field,Sunrisers Hyderabad,2017/04/05,2017,1082591,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,15.1,Rising Pune Supergiant,MS Dhoni,SPD Smith,KH Pandya,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
219,15.2,Rising Pune Supergiant,SPD Smith,MS Dhoni,KH Pandya,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
220,15.3,Rising Pune Supergiant,MS Dhoni,SPD Smith,KH Pandya,4,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
221,15.4,Rising Pune Supergiant,MS Dhoni,SPD Smith,KH Pandya,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
222,15.5,Rising Pune Supergiant,SPD Smith,MS Dhoni,KH Pandya,6,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
223,15.6,Rising Pune Supergiant,SPD Smith,MS Dhoni,KH Pandya,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
224,16.1,Rising Pune Supergiant,SPD Smith,MS Dhoni,JJ Bumrah,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
225,16.2,Rising Pune Supergiant,MS Dhoni,SPD Smith,JJ Bumrah,0,0,caught,MS Dhoni,"""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
226,16.3,Rising Pune Supergiant,MK Tiwary,SPD Smith,JJ Bumrah,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
227,16.4,Rising Pune Supergiant,SPD Smith,MK Tiwary,JJ Bumrah,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
228,16.5,Rising Pune Supergiant,MK Tiwary,SPD Smith,JJ Bumrah,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
229,16.6,Rising Pune Supergiant,MK Tiwary,SPD Smith,JJ Bumrah,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
230,17.1,Rising Pune Supergiant,SPD Smith,MK Tiwary,SL Malinga,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
231,17.2,Rising Pune Supergiant,SPD Smith,MK Tiwary,SL Malinga,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
232,17.3,Rising Pune Supergiant,MK Tiwary,SPD Smith,SL Malinga,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
233,17.4,Rising Pune Supergiant,SPD Smith,MK Tiwary,SL Malinga,0,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
234,17.5,Rising Pune Supergiant,SPD Smith,MK Tiwary,SL Malinga,4,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
235,17.6,Rising Pune Supergiant,SPD Smith,MK Tiwary,SL Malinga,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
236,18.1,Rising Pune Supergiant,SPD Smith,MK Tiwary,JJ Bumrah,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
237,18.2,Rising Pune Supergiant,MK Tiwary,SPD Smith,JJ Bumrah,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
238,18.3,Rising Pune Supergiant,SPD Smith,MK Tiwary,JJ Bumrah,1,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
239,18.4,Rising Pune Supergiant,MK Tiwary,SPD Smith,JJ Bumrah,0,1,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
240,18.5,Rising Pune Supergiant,SPD Smith,MK Tiwary,JJ Bumrah,6,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
241,18.6,Rising Pune Supergiant,SPD Smith,MK Tiwary,JJ Bumrah,2,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
242,19.1,Rising Pune Supergiant,MK Tiwary,SPD Smith,MG Johnson,4,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
243,19.2,Rising Pune Supergiant,MK Tiwary,SPD Smith,MG Johnson,0,0,caught,MK Tiwary,"""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
244,19.3,Rising Pune Supergiant,SPD Smith,DT Christian,MG Johnson,0,0,caught,SPD Smith,"""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
245,19.4,Rising Pune Supergiant,Washington Sundar,DT Christian,MG Johnson,0,1,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
246,19.5,Rising Pune Supergiant,DT Christian,Washington Sundar,MG Johnson,2,0,"""""","""""","""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1
247,19.6,Rising Pune Supergiant,DT Christian,Washington Sundar,MG Johnson,2,0,run out,Washington Sundar,"""Rajiv Gandhi International Stadium",Mumbai Indians,bat,Mumbai Indians,2017/05/21,2017,1082650,1,1